title: Yoonjoo Lee
theme: jekyll-theme-minimal
profile: /assets/img/profile.png
description: I'm interested in building interactive systems to support diverse collaborative tasks (from travel planning to UI design). In particular, I aim to introduce various types of support (e.g., AI, visualizations, or multi-modal input) to enhance communication within collaboration teams.
last_update: January 17, 2021
