title: Yoonjoo Lee
theme: jekyll-theme-minimal
profile: /assets/img/yoonjoo.png
description: My research interest is using data-driven method, especially applying machine learning and NLP model to solve problems in education domain. 
last_update: Feb 18, 2022
